[book]
authors = ["Gavin-Niederman"]
language = "en"
multilingual = false
src = "src"
title = "pros-rs internal docs"

[output.html]
git-repository-url = "https://github.com/pros-rs/internal-documentation"
fold = { enable = true, level = 2 }
site-url = "internals.pros.rs"
mathjax-support = true